site_name: RZL Online Hilfe
site_url: https://hilfe.rzlsoftware.at/
site_description: Die RZL online Hilfe

docs_dir: docs  
  
theme:
  name: material
  language: de
  logo: img/RZL_Herz_weisz.svg
  favicon: img/RZL_Herz_rot.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.footer
  icon:
    repo: fontawesome/brands/github      
  custom_dir: overrides
  palette: 
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  hainz:
    url: https://hainz.rzlsoftware.at
    icon: /img/herz_neuronen.svg
          
extra:
  generator: false
    
copyright: Copyright &copy; 2025 <a href="https://rzlsoftware.at">RZL Software GmbH</a></br><a href="/impressum">Impressum</a> | <a href="/datenschutz">Datenschutz</a>

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css
extra_javascript:
  - scripts/redirect.js
  - scripts/search-filter.js
          
plugins:
  - search:
      lang: de
      prebuild_index: true
  - awesome-pages
  - plugins.program_filter:
      meta_key: program
      exclude:
        - img
        - stylesheets
        - scripts
        - setup

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc
